name: 'Actions Config Rollout'
description: 'Update specified config values in given yaml file'
inputs:
  config_file:  # id of input
    description: 'path to config file to update'
    required: true
  config:
    description: 'new config values to overwrite in file'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
